# Setup
title:               IFT6758 NHL Blog - Team 08
tagline:             'Exploration of the NHL API'
descritpion:         'This blog is about the analysis of some play-by-play data retrieved for the NHL public API: <a href="https://github.com/erunion/sport-api-specifications/tree/master/nhl" target="_blank"></a>.'
url:                 ''
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              An Ni Wu - Thomas Rives - Rui Ze Ma - Alain Fidahoussen
  url:               https://github.com/anw1998 - https://github.com/THOMAS921 - https://github.com/ruizema - https://github.com/AlainFidahoussen
  email:             an.ni.wu@umontreal.ca - thomas.rives@umontreal.ca - rui.ze.ma@umontreal.ca - alain.fidahoussen@umontreal.ca

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
